# .env file variables are available here.

services:
  devenv:
    pull_policy: if_not_present
    image: idelchi/devenv:dev
    build: .
    container_name: devenv
    hostname: devenv
    ports:
      # <host:container>
      - "8888:8888" # GoDoc
      - "10000-10200:10000-10200" # Go Profilers
      - "9090:6419" # grip
    environment:
      - DEVENV
    network_mode: bridge
    user: 1001:1001
    volumes:
      - ${PWD}:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /workspace

  platforms:
    extends: devenv
    build:
      platforms:
        - linux/amd64
        - linux/arm64
