---
version: '3.7'

# .env file variables are available here.

services:
  devenv:
    build: .
    pull_policy: if_not_present
    image: idelchi/devenv:dev
    container_name: devenv
    hostname: devenv
    ports:
      # <host:container>
      - '8888:8888' # GoDoc
      - '10000-10200:10000-10200' # Go Profilers
      - '9090:6419' # grip
    environment:
      - DEVENV
    network_mode: bridge
    user: user
    volumes:
      - ${PWD}:/home/user/ws
      # - ${DEVENV}:${DEVENV} # Possible to mount it inside
    extra_hosts:
      - host:host-gateway
    working_dir: /home/user/ws
