---
version: '3.7'

services:
  devenv:
    build:
      context: .
    pull_policy: never
    image: idelchi/devenv:local
    container_name: devenv
    hostname: devenv
    network_mode: bridge
    user: user
    volumes:
      - .:/home/user/ws
    extra_hosts:
      - host:host-gateway
    working_dir: /home/user/ws
