version: '3'

includes:
  aux: 'taskfiles/Taskfile.aux.yml'
  git: 'taskfiles/Taskfile.git.yml'
  lint: 'taskfiles/Taskfile.lint.yml'
  format: 'taskfiles/Taskfile.format.yml'

silent: true

output: prefixed

tasks:
  # default 'format & lint' target
  # ---------
  default:
    desc: clean, format & lint
    cmds:
      - task: aux
      - task: git
      - task: format
      - task: lint

  # Run a command inside the docker container
  # Usage
  #   - `task docker` to run a shell inside the container
  #   - `task docker -- task format -f` to run a task/command inside the container
  docker:
    cmds:
      - docker rm -f devenv > /dev/null 2>&1 || true
      - docker compose run --build --name devenv --rm --service-ports devenv {{.CLI_ARGS}}
    interactive: true

  # Push to remote
  # Usage:
  #   - `task push` for a default commit message
  #   - `task push -- "My commit message"` for a custom commit message
  push:
    - task: git:diff
    - echo "commit and push? [ctrl-c to cancel]" && read
    - task: git:push
