version: '3'

vars:
  DEVENV: .

dotenv: ['.env']

includes:
  aux:
    taskfile: '{{.DEVENV}}/taskfiles/Taskfile.aux.yml'
    dir: '{{.USER_WORKING_DIR}}'
  git:
    taskfile: '{{.DEVENV}}/taskfiles/Taskfile.git.yml'
    dir: '{{.USER_WORKING_DIR}}'
  lint:
    taskfile: '{{.DEVENV}}/taskfiles/Taskfile.lint.yml'
    dir: '{{.USER_WORKING_DIR}}'
  format:
    taskfile: '{{.DEVENV}}/taskfiles/Taskfile.format.yml'
    dir: '{{.USER_WORKING_DIR}}'

silent: true

output: prefixed

tasks:
  default:
    desc: Clean, format, and lint the codebase
    summary: |
      This task cleans, formats, and lints the codebase.
    cmds:
      - task: aux
      - task: git
      - task: format
      - task: lint

  docker:
    desc: Run commands inside the Docker container
    summary: |
      This task allows you to run commands inside the Docker container.
      Usage:
        - `task docker` to launch the container and enter its shell
        - `task docker -- task <task> -f` to run a task/command inside the container
    cmds:
      - docker rm -f devenv > /dev/null 2>&1 || true
      - docker compose run --build --name devenv --rm --service-ports devenv {{.CLI_ARGS}}
    interactive: true

  push:
    desc: Push changes to the remote repository
    summary: |
      This task pushes changes to the remote repository.
      Usage:
        - `task push` for a default commit message
        - `task push -- "My commit message"` for a custom commit message
    cmds:
      - task: git
      - task: git:push
