version: "3"

vars:
  # Mandatory, otherwise the includes won't work.
  DEVENV: .
  CONFIG_DIR: "{{.DEVENV}}/settings"
  SCRIPTS_DIR: "{{.DEVENV}}/scripts"
  BUILD_DIR: build

includes:
  aux: "{{.DEVENV}}/taskfiles/Taskfile.aux.yml"
  git: "{{.DEVENV}}/taskfiles/Taskfile.git.yml"
  lint: "{{.DEVENV}}/taskfiles/Taskfile.lint.yml"
  format: "{{.DEVENV}}/taskfiles/Taskfile.format.yml"

silent: true

output: prefixed

tasks:
  default:
    desc: Clean, format, and lint the codebase
    summary: |
      This task cleans, formats, and lints the codebase.
    cmds:
      - task: aux:clean
      - task: aux
      - task: git
      - task: format
      - task: lint
    dir: "{{.USER_WORKING_DIR}}"

  docker:
    desc: Run commands inside the Docker container
    summary: |
      This task allows you to run commands inside the Docker container.
      Usage:
        - `task docker` to launch the container and enter its shell
        - `task docker -- --service-ports` to service ports
        - `task docker -- task <task> -f` to run a task/command inside the container
    cmds:
      - docker rm -f devenv > /dev/null 2>&1 || true
      - docker compose -f {{.DEVENV}}/compose.yaml build --build-arg CACHEBUST=$(date +%s) devenv
      - docker compose -f {{.DEVENV}}/compose.yaml run --remove-orphans --rm devenv {{.CLI_ARGS}}
    interactive: true
    dir: "{{.USER_WORKING_DIR}}"

  push:
    desc: Push changes to the remote repository
    summary: |
      This task pushes changes to the remote repository.
      Usage:
        - `task push` for a default commit message
        - `task push -- "My commit message"` for a custom commit message
    cmds:
      - task: git
      - task: git:push
    dir: "{{.USER_WORKING_DIR}}"
