run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    # deprecated
    - execinquery
    - exportloopref
    - gomnd
    # # overly strict
    - exhaustruct
    # # Use named returns when it makes sense
    - nonamedreturns
    # No restrictions on packages
    - depguard

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: "_test.go"
      linters:
        - funlen
        - wrapcheck

    # Exceptions for `main.go` and `config.go`
    - path: "^cmd/.+/(main|config)\\.go$"
      linters:
        - forbidigo
    - path: "main.go$"
      linters:
        - forbidigo

  exclude:
    # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"

linters-settings:
  forbidigo:
    forbid:
      # Encourage using loggers instead of fmt.Print*
      - 'fmt\.Print.*'
      # Discourage exiting the program
      - os.Exit
      - log.Fatal.*

  varnamelen:
    ignore-names:
      - tc
      - ok

  gci:
    sections:
      # std.
      - standard
      # extensions.
      - prefix(golang.org)
      # 3rd party.
      - prefix(github.com)
      # custom
      - prefix(github.com/idelchi)
      - default
    custom-order: true

  gofumpt:
    extra-rules: true

  mnd:
    ignored-functions:
      - time.Duration

  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
