run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # overly strict
    - exhaustruct
    # Use named returns when it makes sense
    - nonamedreturns

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: '_test.go'
      linters:
        - funlen

    - path: '^main.go$'
      linters:
        - forbidigo

linters-settings:
  forbidigo:
    forbid:
      # Encourage using loggers instead of fmt.Print*
      - 'fmt\.Print.*'
      # Discourage exiting the program
      - os.Exit
      - log.Fatal.*

  varnamelen:
    ignore-names:
      - tc

  gci:
    sections:
      # std.
      - standard
      # extensions.
      - prefix(golang.org)
      # 3rd party.
      - prefix(github.com)
      # custom
      - prefix(github.com/idelchi)
      - default
    custom-order: true

  gofumpt:
    extra-rules: true

  gomnd:
    ignored-functions:
      - time.Duration
