default: true

# line-length - Line length
MD013:
  line_length: 120

# no-duplicate-heading/no-duplicate-header Multiple headings with the same content
MD024:
  siblings_only: true

# no-inline-html Inline HTML
MD033: false
