overrides:
  - files: '*.json'
    options:
      trailingComma: 'es5'
      tabWidth: 4
  - files:
      - '*.yml'
    options:
      tabWidth: 2
      singleQuote: true
      bracketSpacing: false
  - files:
      - '*.yaml'
    options:
      tabWidth: 2
      singleQuote: true
      bracketSpacing: false
