extends: default

rules:
  line-length: disable
  document-start: disable
  comments: disable
  truthy:
    ignore: |
      **/.github/workflows

ignore:
  # YAML files in templates directory are assumed to be Helm templates
  '**/templates/*.yaml'
