language: en-gb

dictionaries:
  - bash
  - golang
  - python
  - project-words

dictionaryDefinitions:
  - name: project-words
    path: project-words
  - name: project-words
    path: config/project-words

allowCompoundWords: true
