name: devenv actions
on:
  workflow_call:
    inputs:
      image:
        description: "Docker Image to use"
        default: "idelchi/devenv:latest"
        required: false
        type: string
      devenv:
        description: "Docker Image to use"
        default: ".devenv"
        required: false
        type: string

env:
  DEVENV: ${{ inputs.devenv }}

jobs:
  info:
    runs-on: ubuntu-24.04
    container: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - run: task info

  lint:
    needs: info
    runs-on: ubuntu-24.04
    container: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - run: task lint

  test:
    needs: info
    runs-on: ubuntu-24.04
    container: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - run: task test

  build:
    needs: info
    runs-on: ubuntu-24.04
    container: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - run: task build
