name: devenv

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - main
    tags:
      - "*"

jobs:
  info:
    uses: ./.github/workflows/info.yml

  cleanup:
    uses: ./.github/workflows/cleanup.yml
    if: github.ref == 'refs/heads/dev'
    needs: info
    permissions:
      actions: write
    with:
      branches: dev,main
      endswith: -beta

  verify:
    uses: ./.github/workflows/devenv.yml
    needs: info
    secrets: inherit

  release:
    uses: ./.github/workflows/docker.yml
    if: github.ref == 'refs/heads/main'
    needs: verify
    permissions:
      contents: write
    secrets: inherit
