name: devenv

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  info:
    uses: ./.github/workflows/info.yml

  verify:
    uses: ./.github/workflows/devenv.yml
    needs: info
    secrets: inherit

  release:
    uses: ./.github/workflows/docker.yml
    if: github.ref == 'refs/heads/main'
    needs: verify
    permissions:
      contents: write
    secrets: inherit

  cleanup:
    uses: ./.github/workflows/cleanup.yml
    if: github.ref == 'refs/heads/dev' && always()
    needs: release
    permissions:
      actions: write
    with:
      branches: dev,main
      endswith: -beta
