name: devenv
on: [push, pull_request, workflow_dispatch]

# TODO: [GHRC](https://dev.to/github/publishing-a-docker-image-to-githubs-container-repository-4n50)

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}
  IMAGE: ${{ github.repository }}

  DEVENV: "."

jobs:
  # TODO: This job could be reusable in other workflows
  info:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          # Print out some more information about the environment
          echo github.repository_owner ${{ github.repository_owner }}
          echo github.repository: ${{ github.repository }}
          echo github.actor ${{ github.actor }}
          echo github.event_name: ${{ github.event_name }}
          echo runner.os: ${{ runner.os }}
          echo github.ref: ${{ github.ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref_name: ${{ github.ref_name }}
          echo whoami: $(whoami)

  verify:
    runs-on: ubuntu-24.04
    needs: [info]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image
      # Use inline cache to speed up the build
      # Load it into the local Docker daemon
      - uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.IMAGE }}:dev
          cache-from: type=registry,ref=${{ env.IMAGE }}:dev

      # Run the minimum required tests to validate the image
      # Make sure the current image is being built and used, and not a remote one
      - run: docker compose run --build --rm devenv task lint

      # Build the Docker image and Push it to Docker Hub
      # The cache should still be available from the previous step
      # Push the inline cache to Docker Hub
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE }}:dev
          cache-to: type=inline

  release:
    runs-on: ubuntu-24.04
    needs: verify
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7

  cleanup:
    needs: verify
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/dev'
    continue-on-error: true
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cleanup old builds
        run: >
          gh run list --limit 500
          --workflow github-actions.yml
          --status completed
          --branch dev
          --json databaseId
          -q ".[].databaseId"
          | xargs -n 1 gh run delete

      - name: cleanup old builds
        run: >
          gh run list --limit 500 \
            --workflow github-actions.yml \
            --status completed \
            --json databaseId,headBranch \
            -q '.[] | select(.headBranch | endswith("-beta")) | .databaseId' \
            | xargs -n 1 gh run delete
