name: devenv

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - main
    tags:
      - "*"

jobs:
  info:
    uses: ./.github/workflows/info.yml

  verify:
    uses: ./.github/workflows/devenv.yml
    needs: info
    secrets: inherit

  release:
    uses: ./.github/workflows/docker-merge.yml
    if: github.ref == 'refs/heads/main'
    needs: verify
    permissions:
      contents: write
    secrets: inherit
    with:
      platforms: linux/amd64,linux/arm64
