name: devenv

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # info:
  #   uses: ./.github/workflows/info.yml

  # verify:
  #   needs: info
  #   uses: ./.github/workflows/devenv.yml
  #   secrets:
  #     dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  # release:
  #   # if: github.ref == 'refs/heads/main'
  #   needs: verify
  #   permissions:
  #     contents: write
  #   uses: ./.github/workflows/docker.yml
  #   secrets:
  #     dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  cleanup:
    if: always()
    # needs: release
    permissions:
      actions: write
    uses: ./.github/workflows/cleanup.yml
